version: '3.2'

services:
  postgresql-webdav:
    image: postgres:11.1
    container_name: postgresql-webdav
    restart: unless-stopped
    ports:
      - 35432:5432
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  mysql-webdav:
    image: mysql:5.7
    container_name: mysql-webdav
    restart: unless-stopped
    ports:
      - 33306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes :
      - ./mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
